### ISSUE TITLE
Default Benutzer laden bei anlegen der Datenbank

### ISSUE THREAD

**Issue by pepeblack** [chumm-uffa/chumm-uffa#100]
Die beiden default Benutzer Eder und pepe beim anlegen der DB laden.

**Comment by heeeman** [comment]
Ich würde keine Default User laden, sondern die Startseite bereinigen.

**Comment by pepeblack** [comment]
Ok, einverstanden. Habe mir das noch mal kurz angeschaut und mit 10 Zeilen Code das ganze noch ein wenig verbessert. Ist für's Testen ein wenig einfacher. Können wir einfach raus schmeissen wenn wir abgeben.
