### ISSUE TITLE
Interface node project erstellen

### ISSUE THREAD

**Issue by heeeman** [chumm-uffa/chumm-uffa#11]
Es ist ein node project als Schnittstellenbeschreibung zu erstellen. Dieses soll die Datenstabilität zwischen Client und Server der Rest Aufrufen sichersellen.
Die genaue Ausprägung ist noch zu definieren, es gibt Varianten wie:
- Interface -> Problem gibts nur für TS und node ist JS
- Factory -> Die Daten Objecte werden von Factorys erstellt und geparsed

evtl. lohnt sich auch eine Recherche im Internet über gängige Techniken

**Comment by pepeblack** [comment]
Ist erledigt
