### ISSUE TITLE
Abkärung Routing - Problem mutate meetup

### ISSUE THREAD

**Issue by heeeman** [chumm-uffa/chumm-uffa#21]
Gemäss Plan soll bei den Seiten myMeetups und Suche beim click auf ein meetup auf die Seite Meetup-Detail des entsprechenden Meetups gewechselt werden. Soweit so gut, das passt für alle Fälle AUSSER bei der site myMeetup für MEINE Meetups. Diese brauchen noch eine Möglichkeit editiert zu werden.

Soll das über ein Context Menü gehen?   Ich würde eher einen 'edit' Button auf der rechten Seite vorschlagen.
Was mein Meister Dani dazu?

**Comment by pepeblack** [comment]
Was hälst du davon, wenn wir hier beim Clicken auf die Row der Tabelle auf des editieren der jeweiligen Meetup verzweigen?

**Comment by heeeman** [comment]
Das ist mir als erstes durch den Kopf. Mich stört dabei, dass sich das Verhalten dann von den Row in der Suche und den Requests unterscheidet, bei diesen wollen wir beim click auf die Detailansicht wechseln.

**Comment by pepeblack** [comment]
Ok, dann machen wir das so, wie du oben vorgeschlagen hast, mit dem 'edit' Button.  Einfach umzusetzen und der Benutzer weis genau wie er das editieren kann. Einverstanden?

**Comment by heeeman** [comment]
Die Einigung besagt, es gibt nen edit Button. Umsetzungvorschlag siehe PullRequest #22 " Create meetup module "
