### ISSUE TITLE
Oberserver complete / Observable unsubscribe

### ISSUE THREAD

**Issue by heeeman** [chumm-uffa/chumm-uffa#74]
1. Ein Oberserver muss nach Abschluss (dem letzten next()) complete aufrufen.
2. Ein Observable muss sich nach Abschluss unsubscriben. Wobei ich bin mir nicht sicher ob das nötig ist, wenn der Oberserver complete aufruft. Aber sicher bei subscription auf Forms und so.
Evtl.  lässte es sich testen im dem Flag 'closed' auf dem Subscription Objekt.

Projekt nach entsprechenden Fällen durchsuchen und anpassen. Punkt 1 betrifft primär den Business Service, den Punkt 2 hmm mol luga.

finde folgenden Artikel gut:
https://hackernoon.com/understanding-creating-and-subscribing-to-observables-in-angular-426dbf0b04a3

**Comment by pepeblack** [comment]
Erledigt!
