### ISSUE TITLE
Passwort ändern implementieren

### ISSUE THREAD

**Issue by heeeman** [chumm-uffa/chumm-uffa#91]
Aktuell muss beim Profil bearbeiten immer das Passwort doppelt eingegeben werden. Das ist eher unüblich.
Vorschlag:
Das Profil kann im eingeloggtem Zustand editiert werden ohne Passworteingabe, d.h. die Passwort felder sind ausgeblendet.
Passwort ändern wird auf der Profilseite separat implemeniert, z.b. mit einem Button welcher ein Popup oder ein Segement öffnet.

**Comment by pepeblack** [comment]
Guter Vorschlag
